<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2</name>
   <tag></tag>
   <elementGuidId>42bc1b87-010f-4e44-93fd-edda3610be1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numb2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='numb2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d75f6a40-62b1-4dbe-8f6f-74356a4f430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numb2</value>
      <webElementGuid>9fdf0a28-fcda-4730-b2b1-a324aaa84b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>f5a5a742-06ed-4a81-9122-4aeb56fb6332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numb2&quot;)</value>
      <webElementGuid>79b6a6d8-5391-432d-afa9-7e369142fe9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='numb2']</value>
      <webElementGuid>2dbcdc57-73de-45f8-9ef1-f7c4e26a6312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/section/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/h2/span[2]</value>
      <webElementGuid>0570e3a7-2e4f-433c-b33b-097847151ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::span[2]</value>
      <webElementGuid>c56e0963-1968-4b49-8b61-bf68c7946087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you!'])[1]/preceding::span[1]</value>
      <webElementGuid>003e6819-d333-4923-bb4c-85c7df3a629d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F A Q'])[1]/preceding::span[1]</value>
      <webElementGuid>1a62759e-9313-463f-96f7-a05dbbf076a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>ee3731f9-d1e5-44d6-8a39-42fd346985a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'numb2' and (text() = '7' or . = '7')]</value>
      <webElementGuid>515e5ca2-2e74-4029-8fab-935e2ec13239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
