<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_livechat</name>
   <tag></tag>
   <elementGuidId>9f5c6403-1842-4923-9e34-26061dae85a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hubspot-conversations-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@aria-label=&quot;Chat Widget&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>99e496ab-4f6d-4a0e-8388-60a4c8fa8441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.hubspot.com/conversations-visitor/6856823/threads/utk/8eec973c3ac84d448a64b5d4f8afd6a6?uuid=b1769420b9e0442386aeea70c9215037&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=phptravels.com&amp;inApp53=false&amp;messagesUtk=8eec973c3ac84d448a64b5d4f8afd6a6&amp;url=https%3A%2F%2Fphptravels.com%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false</value>
      <webElementGuid>3b51716c-f5cc-4e4e-bbc3-c565aef98502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hubspot-conversations-iframe</value>
      <webElementGuid>2dd96ca6-fe9c-4e4d-8969-6bcc7d3e0f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>327392d3-89c9-41ce-b08f-ec3a161dbadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chat Widget</value>
      <webElementGuid>633b6491-2efd-4421-ba24-becad073ac15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>chat-widget-iframe</value>
      <webElementGuid>55426e8e-7fe4-421a-8797-dc4b539c2ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hubspot-conversations-iframe&quot;)</value>
      <webElementGuid>39149343-7266-4dc8-93b2-aedbc5b9ad28</webElementGuid>
   </webElementProperties>
</WebElementEntity>
