<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonIntegrations</name>
   <tag></tag>
   <elementGuidId>6eb35b2c-38fb-4d06-8814-aceae13c4dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/ul/li[3]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.arrow.waves-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67e11d82-1d72-42e1-922e-f15ccbc1d6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow waves-effect</value>
      <webElementGuid>ae4e06bb-1caa-43e2-9e58-abf5cc9b2545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://phptravels.com/integrations</value>
      <webElementGuid>d537c210-9723-4f97-bc49-525c06205914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Integrations</value>
      <webElementGuid>4050b959-38b9-4823-bf73-ff82ff9a809b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;nav_left&quot;]/ul[1]/li[3]/div[@class=&quot;link&quot;]/div[@class=&quot;dropdown-content&quot;]/a[@class=&quot;arrow waves-effect&quot;]</value>
      <webElementGuid>6f04b6b6-32a8-4c02-b91d-c1799d99c010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/ul/li[3]/div/div/a[2]</value>
      <webElementGuid>9be6bbb7-b605-492f-8975-c5d8ea044b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Integrations')]</value>
      <webElementGuid>3146f550-85d3-4e75-998a-e9052bfbb8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::a[2]</value>
      <webElementGuid>558dd951-7963-491a-9d0c-0df57640ebdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[2]</value>
      <webElementGuid>4ef10bb9-271f-415b-b718-573cb1542273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customizations'])[1]/preceding::a[1]</value>
      <webElementGuid>fdcba902-8747-4736-8527-14af8c09b17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology'])[1]/preceding::a[2]</value>
      <webElementGuid>a89e72d1-1054-4f44-9179-37f23f4d404e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Integrations']/parent::*</value>
      <webElementGuid>31491ba3-a2f4-4f4f-84c7-ce6d56d782ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://phptravels.com/integrations')]</value>
      <webElementGuid>cdb3b7cd-247c-4b36-b34c-e041f1b2fd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>5b7ac245-e988-47f0-ac70-dbcb91217621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://phptravels.com/integrations' and (text() = 'Integrations' or . = 'Integrations')]</value>
      <webElementGuid>4904058c-7bb6-49da-934e-ad4d8446f0fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
