<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Iconlivechat</name>
   <tag></tag>
   <elementGuidId>18ef1beb-a24e-465c-9609-0e2d8a3130c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[3]/span/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.IconLauncher__BaseLauncher-sc-1jmy5h4-0.IconLauncher__CircleLauncher-sc-1jmy5h4-2.cgNirB.reagan--widget-loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53192675-7e8d-48dc-bd64-4f73041ac55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open live chat</value>
      <webElementGuid>92184556-6f19-441a-8175-6b458b230984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>78ea5c19-1fbf-4d2b-99f6-687818a5eb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IconLauncher__BaseLauncher-sc-1jmy5h4-0 IconLauncher__CircleLauncher-sc-1jmy5h4-2 cgNirB reagan--widget-loaded</value>
      <webElementGuid>63ac2f62-5f69-4047-8fd1-806cebeb6080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;lang-en&quot;]/body[@class=&quot;hubspot messages-body&quot;]/div[@class=&quot;widget&quot;]/div[1]/div[@class=&quot;Application__WidgetAppContainer-sc-1f2l0a1-0 dvBAhE widget-app-container&quot;]/span[3]/span[@class=&quot;p-top-5 display-flex p-left-6 launcher-right-align&quot;]/div[@class=&quot;VizExNotificationBadge__Wrapper-re4uui-0 ZNwvj&quot;]/button[@class=&quot;IconLauncher__BaseLauncher-sc-1jmy5h4-0 IconLauncher__CircleLauncher-sc-1jmy5h4-2 cgNirB reagan--widget-loaded&quot;]</value>
      <webElementGuid>f76d2458-d20b-443e-837e-15092b95488f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span/div/button</value>
      <webElementGuid>0c624964-79b0-4b92-9895-6337a451e3f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
